### ISSUE TITLE
PHP 5.6.30 error

### ISSUE THREAD

**Issue by HyperDevil** [mapbuh/onvif-client-php#1]
PHP 5.6.30

This error Call to undefined method ONVIFMedia::get_system_date_and_time() in /var/www/html/onvif-client-php/inc/ONVIF.inc.php on line 45

`<?php
include( 'inc/ONVIFMedia.inc.php' );
ini_set( 'default_socket_timeout', 1800 ); 
$wsdl    = 'http://127.0.0.1/onvif-client-php/WSDL/media-mod.wsdl';
$service = 'http://192.168.1.2/onvif/device_service';
$username = 'admin';
$password = 'admin';
$client = new ONVIFMedia($wsdl,$service,$username,$password);
try {
    $client->response_dump( 'GetProfiles', $client->get_profiles() );
} catch ( Exception $e ) {
    print "SOAP error occured\n";
    $res = $client->client->__getLastRequest();
    print "Last request:\n";
    print( $res . "\n" );
    $res = $client->client->__getLastResponse();
    print "Last response:\n";
    print( $res . "\n");
}

?>
`

**Comment by mapbuh** [comment]
Fixed in last commit.
